[package]
name = "gba"
version = "0.0.0"
edition = "2024"
authors = ["Braedon Wooding"]

[dependencies]
asm_core = { path = "../asm_core" }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"

[features]
gui = []
