[package]
name = "asm_core"
version = "0.0.0"
edition = "2024"
authors = ["Braedon Wooding"]

[dependencies]
arbitrary-int = { git = "https://github.com/danlehmann/arbitrary-int.git" }
bitbybit = "1.3"
bitpatterns = "0.1"
zerocopy = "0.8"
zerocopy-derive = "0.8"
bitflags = "2.9"
anyhow = "1.0"
